name: Publish NuGet Package from GitHub Release

on:
  release:
    types: [published]

jobs:
  publish-to-github-packages:
    runs-on: ubuntu-latest

    steps:
    - name: Download release asset
      uses: dsaltares/fetch-gh-release-asset@v1.1.0
      with:
        file: '*.nupkg'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to GitHub Packages
      run: dotnet nuget push ./*.nupkg --source https://nuget.pkg.github.com/LuisMiSanVe/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
